MYSQL_DATABASE_HOST='127.0.0.1'
MYSQL_DATABASE_USER='user'
MYSQL_DATABASE_PASSWORD='password'
MYSQL_DATABASE_DB='db'

DEBUG=True
COMPRESS_LEVEL=9
JSONIFY_PRETTYPRINT_REGULAR=False

SECRET_KEY=b'42'

LIMIT_ZONES=100
LIMIT_PROJECTS_PER_ZONE=100
LIMIT_TASKS_PER_PROJECT=100